//! FFI bindings to the pclsync C library.
//!
//! This module provides:
//! - Raw unsafe FFI function declarations
//! - C type definitions and conversions
//! - Callback trampolines for C-to-Rust callbacks
//!
//! # Safety
//!
//! All functions in this module that call into C code are unsafe.
//! Users should prefer the safe wrappers in the `wrapper` module.
//!
//! # Submodules
//!
//! - `raw`: Raw FFI function declarations for pclsync C functions
//! - `types`: C struct type definitions (bindgen-generated and manual)
//! - `callbacks`: Callback trampolines and safe registration functions
//!
//! # Usage
//!
//! The FFI layer is split into three main parts:
//!
//! 1. **Types** (`types` module): Contains struct definitions generated by bindgen
//!    and Rust constants that mirror the C library's constants. Use these types
//!    when you need to pass data to or receive data from C functions.
//!
//! 2. **Raw Functions** (`raw` module): Contains the actual FFI function declarations.
//!    All functions are unsafe and require careful attention to pointer validity,
//!    memory ownership, and thread safety.
//!
//! 3. **Callbacks** (`callbacks` module): Contains safe callback registration and
//!    trampoline functions for C-to-Rust callback invocation.
//!
//! # Example
//!
//! ```ignore
//! use console_client::ffi::{raw, types, callbacks};
//! use console_client::utils::cstring::to_cstring;
//!
//! // Register callbacks before starting sync
//! callbacks::register_status_callback(|status| {
//!     println!("Status changed: {}", status.status);
//! });
//!
//! // Initialize the library
//! unsafe {
//!     let result = raw::psync_init();
//!     if result != 0 {
//!         panic!("Failed to initialize pclsync");
//!     }
//! }
//!
//! // Start sync with the trampoline callback
//! unsafe {
//!     raw::psync_start_sync(
//!         Some(callbacks::status_callback_trampoline),
//!         None,
//!     );
//! }
//!
//! // Get current status
//! let mut status = types::pstatus_t::default();
//! unsafe {
//!     raw::psync_get_status(&mut status);
//! }
//!
//! println!("Current status: {}", types::status_to_string(status.status));
//! ```
//!
//! # Thread Safety
//!
//! The pclsync library uses internal threading. Key thread safety notes:
//!
//! - Callbacks (status, event, notification) are called from a dedicated callback thread
//! - Callbacks are guaranteed not to overlap with each other
//! - Most API functions should be called from the main application thread
//! - Some functions like `psync_network_exception()` are safe to call from any thread
//!
//! # Memory Management
//!
//! Memory returned by pclsync functions typically needs to be freed:
//!
//! - Use `psync_free()` for memory allocated by the library
//! - Some functions return pointers that should NOT be freed (documented per-function)
//! - Always check for null pointers before dereferencing
//!
//! # Callbacks
//!
//! The `callbacks` module provides:
//! - Safe Rust callback registration via `register_*_callback()` functions
//! - Trampoline functions (`*_callback_trampoline`) for C-to-Rust callback invocation
//! - Thread-safe callback data management with panic guards
//! - `CallbackConfig` builder for configuring multiple callbacks at once
//! - Application-level overlay callbacks for interactive mode

pub mod callbacks;
pub mod raw;
pub mod types;

// Re-export commonly used items from types
pub use types::{
    is_error_status,
    is_syncing,
    needs_user_action,
    // Helper functions
    status_to_string,
    PLIST_ALL,
    // List type constants
    PLIST_FILES,
    PLIST_FOLDERS,
    PSTATUS_ACCOUNT_FULL,
    PSTATUS_BAD_LOGIN_DATA,
    PSTATUS_BAD_LOGIN_TOKEN,
    PSTATUS_CONNECTING,
    PSTATUS_DISK_FULL,
    PSTATUS_DOWNLOADING,
    PSTATUS_DOWNLOADINGANDUPLOADING,
    PSTATUS_LOGIN_REQUIRED,
    PSTATUS_OFFLINE,
    PSTATUS_PAUSED,
    // Status constants
    PSTATUS_READY,
    PSTATUS_SCANNING,
    PSTATUS_STOPPED,
    PSTATUS_UPLOADING,
    PSTATUS_USER_MISMATCH,
    // Sync type constants
    PSYNC_DOWNLOAD_ONLY,
    PSYNC_FULL,
    PSYNC_UPLOAD_ONLY,
};

// Re-export the pstatus_t struct
pub use types::pstatus_t;

// Re-export type aliases
pub use types::{
    psync_eventtype_t, psync_fileid_t, psync_folderid_t, psync_listtype_t, psync_syncid_t,
    psync_synctype_t,
};

// Re-export callback types from types module
pub use types::{
    pevent_callback_t, pnotification_callback_t, pstatus_change_callback_t,
    psync_generic_callback_t,
};

// Re-export commonly used items from callbacks module
pub use callbacks::{
    clear_all_callbacks,
    clear_event_callback,
    clear_fs_start_callback,
    clear_notification_callback,
    // Clearing functions
    clear_status_callback,
    event_callback_trampoline,
    fs_start_callback_trampoline,
    notification_callback_trampoline,
    register_event_callback,
    register_fs_start_callback,
    register_notification_callback,
    // Registration functions
    register_status_callback,
    // Trampoline functions
    status_callback_trampoline,
    // Configuration types
    CallbackConfig,
    CallbackPointers,
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_status_constants_exported() {
        // Verify constants are accessible
        assert_eq!(PSTATUS_READY, 0);
        assert_eq!(PSTATUS_DOWNLOADING, 1);
        assert_eq!(PSTATUS_UPLOADING, 2);
    }

    #[test]
    fn test_sync_type_constants() {
        assert_eq!(PSYNC_DOWNLOAD_ONLY, 1);
        assert_eq!(PSYNC_UPLOAD_ONLY, 2);
        assert_eq!(PSYNC_FULL, 3);
    }

    #[test]
    fn test_status_helper_functions() {
        assert_eq!(status_to_string(PSTATUS_READY), "Ready");
        assert!(is_syncing(PSTATUS_DOWNLOADING));
        assert!(!is_syncing(PSTATUS_READY));
        assert!(is_error_status(PSTATUS_LOGIN_REQUIRED));
        assert!(needs_user_action(PSTATUS_BAD_LOGIN_DATA));
    }
}
