//! C type definitions for pclsync FFI bindings.
//!
//! This module provides:
//! - Bindgen-generated struct bindings (included from `$OUT_DIR/bindings.rs`)
//! - Rust-friendly type aliases
//! - Status code constants
//! - Event type constants
//!
//! # Bindgen Types
//!
//! The struct definitions are generated by bindgen during build and included here.
//! They mirror the C struct layouts exactly to ensure ABI compatibility.
//!
//! # Safety
//!
//! These types are designed to cross the FFI boundary. When using pointers
//! within these structs, always verify they are non-null before dereferencing.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

use std::os::raw::c_int;

// Include bindgen-generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ============================================================================
// Status Constants
// ============================================================================

/// Sync status: ready (idle, all synced)
pub const PSTATUS_READY: u32 = 0;
/// Sync status: downloading files
pub const PSTATUS_DOWNLOADING: u32 = 1;
/// Sync status: uploading files
pub const PSTATUS_UPLOADING: u32 = 2;
/// Sync status: both downloading and uploading
pub const PSTATUS_DOWNLOADINGANDUPLOADING: u32 = 3;
/// Sync status: login required
pub const PSTATUS_LOGIN_REQUIRED: u32 = 4;
/// Sync status: bad login credentials
pub const PSTATUS_BAD_LOGIN_DATA: u32 = 5;
/// Sync status: bad authentication token
pub const PSTATUS_BAD_LOGIN_TOKEN: u32 = 6;
/// Sync status: cloud storage is full
pub const PSTATUS_ACCOUNT_FULL: u32 = 7;
/// Sync status: local disk is full
pub const PSTATUS_DISK_FULL: u32 = 8;
/// Sync status: sync is paused
pub const PSTATUS_PAUSED: u32 = 9;
/// Sync status: sync is stopped
pub const PSTATUS_STOPPED: u32 = 10;
/// Sync status: no network connection
pub const PSTATUS_OFFLINE: u32 = 11;
/// Sync status: connecting to server
pub const PSTATUS_CONNECTING: u32 = 12;
/// Sync status: scanning local files
pub const PSTATUS_SCANNING: u32 = 13;
/// Sync status: logged in user doesn't match expected
pub const PSTATUS_USER_MISMATCH: u32 = 14;

// ============================================================================
// Event Type Constants
// ============================================================================

/// Event type flag: local operation
pub const PEVENT_TYPE_LOCAL: u32 = 0 << 0;
/// Event type flag: remote operation
pub const PEVENT_TYPE_REMOTE: u32 = 1 << 0;
/// Event type flag: file operation
pub const PEVENT_TYPE_FILE: u32 = 0 << 1;
/// Event type flag: folder operation
pub const PEVENT_TYPE_FOLDER: u32 = 1 << 1;
/// Event type flag: create operation
pub const PEVENT_TYPE_CREATE: u32 = 0 << 2;
/// Event type flag: delete operation
pub const PEVENT_TYPE_DELETE: u32 = 1 << 2;
/// Event type flag: rename operation
pub const PEVENT_TYPE_RENAME: u32 = 2 << 2;
/// Event type flag: operation started
pub const PEVENT_TYPE_START: u32 = 0 << 5;
/// Event type flag: operation finished
pub const PEVENT_TYPE_FINISH: u32 = 1 << 5;
/// Event type flag: operation succeeded
pub const PEVENT_TYPE_SUCCESS: u32 = 0 << 6;
/// Event type flag: operation failed
pub const PEVENT_TYPE_FAIL: u32 = 1 << 6;

/// First user-related event ID
pub const PEVENT_FIRST_USER_EVENT: u32 = 1 << 30;
/// First share-related event ID
pub const PEVENT_FIRST_SHARE_EVENT: u32 = PEVENT_FIRST_USER_EVENT + 200;

// Combined event types
/// Event: local folder was created (replicated from remote)
pub const PEVENT_LOCAL_FOLDER_CREATED: u32 =
    PEVENT_TYPE_LOCAL + PEVENT_TYPE_FOLDER + PEVENT_TYPE_CREATE;
/// Event: remote folder was created (replicated from local)
pub const PEVENT_REMOTE_FOLDER_CREATED: u32 =
    PEVENT_TYPE_REMOTE + PEVENT_TYPE_FOLDER + PEVENT_TYPE_CREATE;
/// Event: file download started
pub const PEVENT_FILE_DOWNLOAD_STARTED: u32 =
    PEVENT_TYPE_LOCAL + PEVENT_TYPE_FILE + PEVENT_TYPE_CREATE + PEVENT_TYPE_START;
/// Event: file download finished successfully
pub const PEVENT_FILE_DOWNLOAD_FINISHED: u32 = PEVENT_TYPE_LOCAL
    + PEVENT_TYPE_FILE
    + PEVENT_TYPE_CREATE
    + PEVENT_TYPE_FINISH
    + PEVENT_TYPE_SUCCESS;
/// Event: file download failed
pub const PEVENT_FILE_DOWNLOAD_FAILED: u32 = PEVENT_TYPE_LOCAL
    + PEVENT_TYPE_FILE
    + PEVENT_TYPE_CREATE
    + PEVENT_TYPE_FINISH
    + PEVENT_TYPE_FAIL;
/// Event: file upload started
pub const PEVENT_FILE_UPLOAD_STARTED: u32 =
    PEVENT_TYPE_REMOTE + PEVENT_TYPE_FILE + PEVENT_TYPE_CREATE + PEVENT_TYPE_START;
/// Event: file upload finished successfully
pub const PEVENT_FILE_UPLOAD_FINISHED: u32 = PEVENT_TYPE_REMOTE
    + PEVENT_TYPE_FILE
    + PEVENT_TYPE_CREATE
    + PEVENT_TYPE_FINISH
    + PEVENT_TYPE_SUCCESS;
/// Event: file upload failed
pub const PEVENT_FILE_UPLOAD_FAILED: u32 = PEVENT_TYPE_REMOTE
    + PEVENT_TYPE_FILE
    + PEVENT_TYPE_CREATE
    + PEVENT_TYPE_FINISH
    + PEVENT_TYPE_FAIL;
/// Event: local folder was deleted
pub const PEVENT_LOCAL_FOLDER_DELETED: u32 =
    PEVENT_TYPE_LOCAL + PEVENT_TYPE_FOLDER + PEVENT_TYPE_DELETE;
/// Event: remote folder was deleted
pub const PEVENT_REMOTE_FOLDER_DELETED: u32 =
    PEVENT_TYPE_REMOTE + PEVENT_TYPE_FOLDER + PEVENT_TYPE_DELETE;
/// Event: local file was deleted
pub const PEVENT_LOCAL_FILE_DELETED: u32 =
    PEVENT_TYPE_LOCAL + PEVENT_TYPE_FILE + PEVENT_TYPE_DELETE;
/// Event: remote file was deleted
pub const PEVENT_REMOTE_FILE_DELETED: u32 =
    PEVENT_TYPE_REMOTE + PEVENT_TYPE_FILE + PEVENT_TYPE_DELETE;
/// Event: local folder was renamed
pub const PEVENT_LOCAL_FOLDER_RENAMED: u32 =
    PEVENT_TYPE_LOCAL + PEVENT_TYPE_FOLDER + PEVENT_TYPE_RENAME;

/// Event: user info changed
pub const PEVENT_USERINFO_CHANGED: u32 = PEVENT_FIRST_USER_EVENT;
/// Event: used quota changed
pub const PEVENT_USEDQUOTA_CHANGED: u32 = PEVENT_FIRST_USER_EVENT + 1;

// Share events
/// Event: incoming share request
pub const PEVENT_SHARE_REQUESTIN: u32 = PEVENT_FIRST_SHARE_EVENT;
/// Event: outgoing share request
pub const PEVENT_SHARE_REQUESTOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 1;
/// Event: incoming share accepted
pub const PEVENT_SHARE_ACCEPTIN: u32 = PEVENT_FIRST_SHARE_EVENT + 2;
/// Event: outgoing share accepted
pub const PEVENT_SHARE_ACCEPTOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 3;
/// Event: incoming share declined
pub const PEVENT_SHARE_DECLINEIN: u32 = PEVENT_FIRST_SHARE_EVENT + 4;
/// Event: outgoing share declined
pub const PEVENT_SHARE_DECLINEOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 5;
/// Event: incoming share cancelled
pub const PEVENT_SHARE_CANCELIN: u32 = PEVENT_FIRST_SHARE_EVENT + 6;
/// Event: outgoing share cancelled
pub const PEVENT_SHARE_CANCELOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 7;
/// Event: incoming share removed
pub const PEVENT_SHARE_REMOVEIN: u32 = PEVENT_FIRST_SHARE_EVENT + 8;
/// Event: outgoing share removed
pub const PEVENT_SHARE_REMOVEOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 9;
/// Event: incoming share modified
pub const PEVENT_SHARE_MODIFYIN: u32 = PEVENT_FIRST_SHARE_EVENT + 10;
/// Event: outgoing share modified
pub const PEVENT_SHARE_MODIFYOUT: u32 = PEVENT_FIRST_SHARE_EVENT + 11;

// ============================================================================
// Notification Action Constants
// ============================================================================

/// Notification action: no action
pub const PNOTIFICATION_ACTION_NONE: u8 = 0;
/// Notification action: go to folder
pub const PNOTIFICATION_ACTION_GO_TO_FOLDER: u8 = 1;
/// Notification action: go to URL
pub const PNOTIFICATION_ACTION_GO_TO_URL: u8 = 2;
/// Notification action: share request
pub const PNOTIFICATION_ACTION_SHARE_REQUEST: u8 = 3;

// ============================================================================
// Sync Type Constants
// ============================================================================

/// Sync type: download only
pub const PSYNC_DOWNLOAD_ONLY: u32 = 1;
/// Sync type: upload only
pub const PSYNC_UPLOAD_ONLY: u32 = 2;
/// Sync type: full bidirectional sync
pub const PSYNC_FULL: u32 = 3;
/// Sync type: minimum valid value
pub const PSYNC_SYNCTYPE_MIN: u32 = 1;
/// Sync type: maximum valid value
pub const PSYNC_SYNCTYPE_MAX: u32 = 3;

// ============================================================================
// Error Constants
// ============================================================================

/// Error: local folder not found
pub const PERROR_LOCAL_FOLDER_NOT_FOUND: u32 = 1;
/// Error: remote folder not found
pub const PERROR_REMOTE_FOLDER_NOT_FOUND: u32 = 2;
/// Error: database open failed
pub const PERROR_DATABASE_OPEN: u32 = 3;
/// Error: no home directory
pub const PERROR_NO_HOMEDIR: u32 = 4;
/// Error: SSL init failed
pub const PERROR_SSL_INIT_FAILED: u32 = 5;
/// Error: database error
pub const PERROR_DATABASE_ERROR: u32 = 6;
/// Error: local folder access denied
pub const PERROR_LOCAL_FOLDER_ACC_DENIED: u32 = 7;
/// Error: remote folder access denied
pub const PERROR_REMOTE_FOLDER_ACC_DENIED: u32 = 8;
/// Error: folder already syncing
pub const PERROR_FOLDER_ALREADY_SYNCING: u32 = 9;
/// Error: invalid sync type
pub const PERROR_INVALID_SYNCTYPE: u32 = 10;
/// Error: offline
pub const PERROR_OFFLINE: u32 = 11;
/// Error: invalid sync ID
pub const PERROR_INVALID_SYNCID: u32 = 12;
/// Error: parent or subfolder already syncing
pub const PERROR_PARENT_OR_SUBFOLDER_ALREADY_SYNCING: u32 = 13;
/// Error: local path is on pCloud Drive
pub const PERROR_LOCAL_IS_ON_PDRIVE: u32 = 14;

// ============================================================================
// List Type Constants
// ============================================================================

/// List type: files only
pub const PLIST_FILES: u32 = 1;
/// List type: folders only
pub const PLIST_FOLDERS: u32 = 2;
/// List type: both files and folders
pub const PLIST_ALL: u32 = 3;

// ============================================================================
// Permission Constants
// ============================================================================

/// Permission: read
pub const PSYNC_PERM_READ: u32 = 1;
/// Permission: create
pub const PSYNC_PERM_CREATE: u32 = 2;
/// Permission: modify
pub const PSYNC_PERM_MODIFY: u32 = 4;
/// Permission: delete
pub const PSYNC_PERM_DELETE: u32 = 8;
/// Permission: all permissions
pub const PSYNC_PERM_ALL: u32 =
    PSYNC_PERM_READ | PSYNC_PERM_CREATE | PSYNC_PERM_MODIFY | PSYNC_PERM_DELETE;
/// Permission: write permissions (create, modify, delete)
pub const PSYNC_PERM_WRITE: u32 = PSYNC_PERM_CREATE | PSYNC_PERM_MODIFY | PSYNC_PERM_DELETE;

// ============================================================================
// Crypto Error Constants
// ============================================================================

/// Crypto setup: success
pub const PSYNC_CRYPTO_SETUP_SUCCESS: c_int = 0;
/// Crypto setup: not supported
pub const PSYNC_CRYPTO_SETUP_NOT_SUPPORTED: c_int = -1;
/// Crypto setup: key generation failed
pub const PSYNC_CRYPTO_SETUP_KEYGEN_FAILED: c_int = 1;
/// Crypto setup: cannot connect
pub const PSYNC_CRYPTO_SETUP_CANT_CONNECT: c_int = 2;
/// Crypto setup: not logged in
pub const PSYNC_CRYPTO_SETUP_NOT_LOGGED_IN: c_int = 3;
/// Crypto setup: already set up
pub const PSYNC_CRYPTO_SETUP_ALREADY_SETUP: c_int = 4;
/// Crypto setup: unknown error
pub const PSYNC_CRYPTO_SETUP_UNKNOWN_ERROR: c_int = 5;

/// Crypto start: success
pub const PSYNC_CRYPTO_START_SUCCESS: c_int = 0;
/// Crypto start: not supported
pub const PSYNC_CRYPTO_START_NOT_SUPPORTED: c_int = -1;
/// Crypto start: already started
pub const PSYNC_CRYPTO_START_ALREADY_STARTED: c_int = 1;
/// Crypto start: cannot connect
pub const PSYNC_CRYPTO_START_CANT_CONNECT: c_int = 2;
/// Crypto start: not logged in
pub const PSYNC_CRYPTO_START_NOT_LOGGED_IN: c_int = 3;
/// Crypto start: not set up
pub const PSYNC_CRYPTO_START_NOT_SETUP: c_int = 4;
/// Crypto start: unknown key format
pub const PSYNC_CRYPTO_START_UNKNOWN_KEY_FORMAT: c_int = 5;
/// Crypto start: bad password
pub const PSYNC_CRYPTO_START_BAD_PASSWORD: c_int = 6;
/// Crypto start: keys don't match
pub const PSYNC_CRYPTO_START_KEYS_DONT_MATCH: c_int = 7;
/// Crypto start: unknown error
pub const PSYNC_CRYPTO_START_UNKNOWN_ERROR: c_int = 8;

/// Crypto stop: success
pub const PSYNC_CRYPTO_STOP_SUCCESS: c_int = 0;
/// Crypto stop: not supported
pub const PSYNC_CRYPTO_STOP_NOT_SUPPORTED: c_int = -1;
/// Crypto stop: not started
pub const PSYNC_CRYPTO_STOP_NOT_STARTED: c_int = 1;

/// Crypto hint: success
pub const PSYNC_CRYPTO_HINT_SUCCESS: c_int = 0;
/// Crypto hint: not supported
pub const PSYNC_CRYPTO_HINT_NOT_SUPPORTED: c_int = -1;
/// Crypto hint: not provided
pub const PSYNC_CRYPTO_HINT_NOT_PROVIDED: c_int = 1;
/// Crypto hint: cannot connect
pub const PSYNC_CRYPTO_HINT_CANT_CONNECT: c_int = 2;
/// Crypto hint: not logged in
pub const PSYNC_CRYPTO_HINT_NOT_LOGGED_IN: c_int = 3;
/// Crypto hint: unknown error
pub const PSYNC_CRYPTO_HINT_UNKNOWN_ERROR: c_int = 4;

/// Generic crypto: success
pub const PSYNC_CRYPTO_SUCCESS: c_int = 0;
/// Generic crypto: not started
pub const PSYNC_CRYPTO_NOT_STARTED: c_int = -1;
/// Generic crypto: RSA error
pub const PSYNC_CRYPTO_RSA_ERROR: c_int = -2;
/// Generic crypto: folder not found
pub const PSYNC_CRYPTO_FOLDER_NOT_FOUND: c_int = -3;
/// Generic crypto: file not found
pub const PSYNC_CRYPTO_FILE_NOT_FOUND: c_int = -4;
/// Generic crypto: invalid key
pub const PSYNC_CRYPTO_INVALID_KEY: c_int = -5;
/// Generic crypto: cannot connect
pub const PSYNC_CRYPTO_CANT_CONNECT: c_int = -6;
/// Generic crypto: folder not encrypted
pub const PSYNC_CRYPTO_FOLDER_NOT_ENCRYPTED: c_int = -7;
/// Generic crypto: internal error
pub const PSYNC_CRYPTO_INTERNAL_ERROR: c_int = -8;

/// Invalid folder ID sentinel value
pub const PSYNC_CRYPTO_INVALID_FOLDERID: u64 = u64::MAX;

/// Invalid sync ID sentinel value
pub const PSYNC_INVALID_SYNCID: u32 = u32::MAX;

// ============================================================================
// Helper Functions
// ============================================================================

/// Convert a sync status code to a human-readable string.
pub fn status_to_string(status: u32) -> &'static str {
    match status {
        PSTATUS_READY => "Ready",
        PSTATUS_DOWNLOADING => "Downloading",
        PSTATUS_UPLOADING => "Uploading",
        PSTATUS_DOWNLOADINGANDUPLOADING => "Syncing",
        PSTATUS_LOGIN_REQUIRED => "Login Required",
        PSTATUS_BAD_LOGIN_DATA => "Invalid Credentials",
        PSTATUS_BAD_LOGIN_TOKEN => "Invalid Token",
        PSTATUS_ACCOUNT_FULL => "Account Full",
        PSTATUS_DISK_FULL => "Disk Full",
        PSTATUS_PAUSED => "Paused",
        PSTATUS_STOPPED => "Stopped",
        PSTATUS_OFFLINE => "Offline",
        PSTATUS_CONNECTING => "Connecting",
        PSTATUS_SCANNING => "Scanning",
        PSTATUS_USER_MISMATCH => "User Mismatch",
        _ => "Unknown",
    }
}

/// Check if a status indicates the client is actively syncing.
pub fn is_syncing(status: u32) -> bool {
    matches!(
        status,
        PSTATUS_DOWNLOADING | PSTATUS_UPLOADING | PSTATUS_DOWNLOADINGANDUPLOADING
    )
}

/// Check if a status indicates an error condition.
pub fn is_error_status(status: u32) -> bool {
    matches!(
        status,
        PSTATUS_LOGIN_REQUIRED
            | PSTATUS_BAD_LOGIN_DATA
            | PSTATUS_BAD_LOGIN_TOKEN
            | PSTATUS_ACCOUNT_FULL
            | PSTATUS_DISK_FULL
            | PSTATUS_USER_MISMATCH
    )
}

/// Check if a status indicates the client needs user action.
pub fn needs_user_action(status: u32) -> bool {
    matches!(
        status,
        PSTATUS_LOGIN_REQUIRED
            | PSTATUS_BAD_LOGIN_DATA
            | PSTATUS_BAD_LOGIN_TOKEN
            | PSTATUS_USER_MISMATCH
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_status_to_string() {
        assert_eq!(status_to_string(PSTATUS_READY), "Ready");
        assert_eq!(status_to_string(PSTATUS_DOWNLOADING), "Downloading");
        assert_eq!(status_to_string(PSTATUS_OFFLINE), "Offline");
        assert_eq!(status_to_string(999), "Unknown");
    }

    #[test]
    fn test_is_syncing() {
        assert!(is_syncing(PSTATUS_DOWNLOADING));
        assert!(is_syncing(PSTATUS_UPLOADING));
        assert!(is_syncing(PSTATUS_DOWNLOADINGANDUPLOADING));
        assert!(!is_syncing(PSTATUS_READY));
        assert!(!is_syncing(PSTATUS_OFFLINE));
    }

    #[test]
    fn test_is_error_status() {
        assert!(is_error_status(PSTATUS_LOGIN_REQUIRED));
        assert!(is_error_status(PSTATUS_BAD_LOGIN_DATA));
        assert!(is_error_status(PSTATUS_ACCOUNT_FULL));
        assert!(!is_error_status(PSTATUS_READY));
        assert!(!is_error_status(PSTATUS_DOWNLOADING));
    }

    #[test]
    fn test_needs_user_action() {
        assert!(needs_user_action(PSTATUS_LOGIN_REQUIRED));
        assert!(needs_user_action(PSTATUS_BAD_LOGIN_DATA));
        assert!(!needs_user_action(PSTATUS_READY));
        assert!(!needs_user_action(PSTATUS_ACCOUNT_FULL));
    }

    #[test]
    fn test_sync_type_constants() {
        assert!(PSYNC_DOWNLOAD_ONLY >= PSYNC_SYNCTYPE_MIN);
        assert!(PSYNC_DOWNLOAD_ONLY <= PSYNC_SYNCTYPE_MAX);
        assert!(PSYNC_UPLOAD_ONLY >= PSYNC_SYNCTYPE_MIN);
        assert!(PSYNC_UPLOAD_ONLY <= PSYNC_SYNCTYPE_MAX);
        assert!(PSYNC_FULL >= PSYNC_SYNCTYPE_MIN);
        assert!(PSYNC_FULL <= PSYNC_SYNCTYPE_MAX);
    }

    #[test]
    fn test_permission_constants() {
        assert_eq!(PSYNC_PERM_ALL, 0b1111);
        assert_eq!(
            PSYNC_PERM_WRITE,
            PSYNC_PERM_CREATE | PSYNC_PERM_MODIFY | PSYNC_PERM_DELETE
        );
    }
}
